version: "3"
services: 
  web:
    image: svork/first_docker_repo:delicia
    deploy:
      replicas: 5
      resources:
        limits:
          cpu: "0.1"
          memory: 50M
      restart-policy:
        condition: on-failure
    ports:
      - "40000:80"
    networks:
      - webnet
networks:
  webnet:
